const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
    //admin
    // ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',

    //Admin
    FETCH_GENDER_START: "FETCH_GENDER_START",
    FETCH_GENDER_SUCCESS: "FETCH_GENDER_SUCCESS",
    FETCH_GENDER_FAILED: "FETCH_GENDER_FAILED",

    FETCH_POSITION_SUCCESS: "FETCH_POSITION_SUCCESS",
    FETCH_POSITION_FAILD: "FETCH_POSITION_FAILED",

    FETCH_ROLE_SUCCESS: "FETCH_ROLE_SUCCESS",
    FETCH_ROLE_FAILD: "FETCH_ROLE_FAILED",

    CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
    CREATE_USER_FAILED: "CREATE_USER_FAILED",

    FETCH_ALL_USERS_SUCCESS: "FETCH_ALL_USERS_SUCCESS",
    FETCH_ALL_USERS_FAILED: "FETCH_ALL_USERS_FAILED",

    FETCH_DELETE_USERS_SUCCESS: "FETCH_DELETE_USERS_SUCCESS",
    FETCH_DELETE_USERS_FAILED: "FETCH_DELETE_USERS_FAILED",

    FETCH_EDIT_USERS_SUCCESS: "FETCH_EDIT_USERS_SUCCESS",
    FETCH_EDIT_USERS_FAILED: "FETCH_EDIT_USERS_FAILED",

    FETCH_TOP_DOCTORS_SUCCESS: "FETCH_TOP_DOCTORS_SUCCESS",
    FETCH_TOP_DOCTORS_FAILED: "FETCH_TOP_DOCTORS_FAILED",

    FETCH_ALL_DOCTORS_SUCCESS: "FETCH_ALL_DOCTORS_SUCCESS",
    FETCH_ALL_DOCTORS_FAILED: "FETCH_ALL_DOCTORS_FAILED",

    SAVE_INFO_DOCTORS_SUCCESS: "SAVE_INFO_DOCTORS_SUCCESS",
    SAVE_INFO_DOCTORS_FAILED: "SAVE_INFO_DOCTORS_FAILED",

    FETCH_DETAIL_INFO_DOCTORS_SUCCESS: "FETCH_DETAIL_INFO_DOCTORS_SUCCESS",
    FETCH_DETAIL_INFO_DOCTORS_FAILED: "FETCH_DETAIL_INFO_DOCTORS_FAILED",

    FETCH_SCHEDULE_TIME_DOCTORS_SUCCESS: "FETCH_SCHEDULE_TIME_DOCTORS_SUCCESS",
    FETCH_SCHEDULE_TIME_DOCTORS_FAILED: "FETCH_SCHEDULE_TIME_DOCTORS_FAILED",

    FETCH_REQUIRED_DOCTOR_INFOR_START: 'FETCH_REQUIRED_DOCTOR_INFOR_START',
    FETCH_REQUIRED_DOCTOR_INFOR_SUCCESS: "FETCH_REQUIRED_DOCTOR_INFOR_SUCCESS",
    FETCH_REQUIRED_DOCTOR_INFOR_FAILED: "FETCH_REQUIRED_DOCTOR_INFOR_FAILED",

    FETCH_EXTRA_INFO_DOCTOR_SUCCESS: "FETCH_EXTRA_INFO_DOCTOR_SUCCESS",
    FETCH_EXTRA_INFO_DOCTOR_FAILED: "FETCH_EXTRA_INFO_DOCTOR_FAILED",

    FETCH_ALL_SPECIALTY_SUCCESS: "FETCH_ALL_SPECIALTY_SUCCESS",
    FETCH_ALL_SPECIALTY_FAILED: "FETCH_ALL_SPECIALTY_FAILED",

    FETCH_ALL_CLINIC_SUCCESS: "FETCH_ALL_CLINIC_SUCCESS",
    FETCH_ALL_CLINIC_FAILED: "FETCH_ALL_CLINIC_FAILED",

    FETCH_ALL_HANDBOOK_SUCCESS: "FETCH_ALL_HANDBOOK_SUCCESS",
    FETCH_ALL_HANDBOOK_FAILED: "FETCH_ALL_HANDBOOK_FAILED",

    FETCH_HISTORY_BOOKING_SUCCESS: "FETCH_HISTORY_BOOKING_SUCCESS",
    FETCH_HISTORY_BOOKING_FAILED: "FETCH_HISTORY_BOOKING_FAILED",
})

export default actionTypes;